import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Header from '@/components/Header';

const pretendard = localFont({
  src: '../fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const AppLayout = ({
  children
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="ko">
      <body
        className={`font-pretendard ${pretendard.variable} max-w-[500px] mx-auto bg-baseBackground`}
      >
        <div className="fixed top-0 left-1/2 w-full max-w-[500px] h-full bg-white transform -translate-x-1/2 z-[-1] pointer-events-none mx-auto" />
        <QueryProvider>
          <Header />
          {children}
        </QueryProvider>
      </body>
    </html>
  );
};

export default AppLayout;
